export const api = window.api;

export type {
  DbConfig,
  AuthUser,
  SessionUser,
  CompanySummary,
  CompanyRecord,
  CompanyInput,
  CompanyStatus,
  UserRecord,
  UserInput,
  ReportsSummary,
  ShiftGroupRecord,
  ShiftGroupInput,
  ShiftRecord,
  ShiftInput,
  ProviderGroupRecord,
  ProviderGroupInput,
  ProviderRecord,
  ProviderInput,
  BuyerGroupRecord,
  BuyerGroupInput,
  BuyerRecord,
  BuyerInput,
  ItemGroupRecord,
  ItemGroupInput,
  ItemRecord,
  ItemInput,
  ItemSchemeRecord,
  ItemSchemeInput,
  ItemSchemeWithPrizes,
  DrawRecord,
  DrawInput,
  DrawResultRecord,
  DrawResultInput,
  WinningTicketRecord,
  WinningTicketInput,
  AuditLogRecord,
  TicketSearchResult,
  TransactionRecord,
  TransactionInput,
  TransactionType,
  BuyerSaleSummary,
  ProviderPurchaseSummary,
  TicketValidationResult,
} from '../../shared/types';
